import { SYSTEM_ID } from '@/modules/user/seed/users';
import type { Prisma } from '@/prisma/client';

export const MUSCLES: Prisma.MusclesCreateManyInput[] = [
  {
    id: 1,
    muscularGroupId: 1,
    userId: SYSTEM_ID,
    name: 'Biceps',
  },
  {
    id: 2,
    muscularGroupId: 1,
    userId: SYSTEM_ID,
    name: 'Biceps Long Head',
  },
  {
    id: 3,
    muscularGroupId: 1,
    userId: SYSTEM_ID,
    name: 'Biceps Short Head',
  },
  {
    id: 4,
    muscularGroupId: 2,
    userId: SYSTEM_ID,
    name: 'Forearms',
  },
  {
    id: 5,
    muscularGroupId: 2,
    userId: SYSTEM_ID,
    name: 'Anterior Forearms',
  },
  {
    id: 6,
    muscularGroupId: 2,
    userId: SYSTEM_ID,
    name: 'Rear Forearms',
  },
  {
    id: 7,
    muscularGroupId: 3,
    userId: SYSTEM_ID,
    name: 'Shoulders',
  },
  {
    id: 8,
    muscularGroupId: 3,
    userId: SYSTEM_ID,
    name: 'Anterior Shoulders',
  },
  {
    id: 9,
    muscularGroupId: 3,
    userId: SYSTEM_ID,
    name: 'Lateral Shoulders',
  },
  {
    id: 10,
    muscularGroupId: 3,
    userId: SYSTEM_ID,
    name: 'Rear Shoulders',
  },
  {
    id: 11,
    muscularGroupId: 4,
    userId: SYSTEM_ID,
    name: 'Triceps',
  },
  {
    id: 12,
    muscularGroupId: 4,
    userId: SYSTEM_ID,
    name: 'Triceps Long Head',
  },
  {
    id: 13,
    muscularGroupId: 4,
    userId: SYSTEM_ID,
    name: 'Triceps Short Head',
  },
  {
    id: 14,
    muscularGroupId: 5,
    userId: SYSTEM_ID,
    name: 'Abductors',
  },
  {
    id: 15,
    muscularGroupId: 6,
    userId: SYSTEM_ID,
    name: 'Calves',
  },
  {
    id: 16,
    muscularGroupId: 7,
    userId: SYSTEM_ID,
    name: 'Glutes',
  },
  {
    id: 17,
    muscularGroupId: 8,
    userId: SYSTEM_ID,
    name: 'Hamstrings',
  },
  {
    id: 18,
    muscularGroupId: 9,
    userId: SYSTEM_ID,
    name: 'Quadriceps',
  },
  {
    id: 19,
    muscularGroupId: 9,
    userId: SYSTEM_ID,
    name: 'Rectus Femoris',
  },
  {
    id: 20,
    muscularGroupId: 9,
    userId: SYSTEM_ID,
    name: 'Vastus Lateralis',
  },
  {
    id: 21,
    muscularGroupId: 9,
    userId: SYSTEM_ID,
    name: 'Vastus Medialis',
  },
  {
    id: 22,
    muscularGroupId: 10,
    userId: SYSTEM_ID,
    name: 'Abdominals',
  },
  {
    id: 23,
    muscularGroupId: 10,
    userId: SYSTEM_ID,
    name: 'Lower Abdominals',
  },
  {
    id: 24,
    muscularGroupId: 10,
    userId: SYSTEM_ID,
    name: 'Upper Abdominals',
  },
  {
    id: 25,
    muscularGroupId: 11,
    userId: SYSTEM_ID,
    name: 'Back',
  },
  {
    id: 26,
    muscularGroupId: 11,
    userId: SYSTEM_ID,
    name: 'Bibs',
  },
  {
    id: 27,
    muscularGroupId: 11,
    userId: SYSTEM_ID,
    name: 'Lumbar',
  },
  {
    id: 28,
    muscularGroupId: 11,
    userId: SYSTEM_ID,
    name: 'Trapezius',
  },
  {
    id: 29,
    muscularGroupId: 12,
    userId: SYSTEM_ID,
    name: 'Pectorals',
  },
  {
    id: 30,
    muscularGroupId: 12,
    userId: SYSTEM_ID,
    name: 'Lower Pectorals',
  },
  {
    id: 31,
    muscularGroupId: 12,
    userId: SYSTEM_ID,
    name: 'Middle Pectorals',
  },
  {
    id: 32,
    muscularGroupId: 12,
    userId: SYSTEM_ID,
    name: 'Upper Pectorals',
  },
];
